version: '3'

services:
  web:
    image: nginx:alpine
    container_name: example-webapp
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=host.example.com
      - VIRTUAL_PORT=APPLICATION_PORT
      - LETSENCRYPT_HOST=host.example.com
      - LETSENCRYPT_EMAIL=no-one@example.com
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
