version: '3'
services:
  reverseproxy:
    image: nginx:latest
    container_name: prod_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - ENV=prodcution
      - APPLICATION_URL=http://localhost
    networks:
      - web

  flask_app:
    depends_on:
      - reverseproxy
    image: simple-flask_gunicorn_app:latest
    restart: always
    networks:
      - web
    ports:
      - "80"
  
networks:
  web: